export const defaultRoute = {
    UnauthenticatedHome: '/',
    Login: '/login',
    RegisterCustomer: '/register-customer',
    RegisterBusiness: '/register-business',
    Search: '/search',
    Profile: '/profile',
    Service: '/service',
    Book: '/book',
    BookManagement: '/book-management',
    Company: '/company',
    VerifyEmail: '/verify-email',
    ResetPassword: '/reset-password',
    BusinessDashboard: '/business-dashboard',
};
